version: "3.0"

services:
  api:
    container_name: "post_analyzer_api"
    build: ../api
    volumes:
      - ../api/src:/app
    command:
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload --debug
    restart: always
    tty: true
    ports:
      - 8000:8000